### PR TITLE
Install setuptools

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
I installed `pre-commit` using `sudo apt install pre-commit`. Note: the instructions provided [here](https://pre-commit.com/#install) suggest using `pip` but this does not work smoothly since Ubuntu24.04 due to some policy changes regarding the `--user` flag.

When trying to run `pre-commit` in our main preCICE repository I got the following problem:
```
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

Traceback (most recent call last):
  File "/home/benjamin/.cache/pre-commit/repo8_dq7otg/py_env-python3/bin/clang-format", line 5, in <module>
    from clang_format import clang_format
  File "/home/benjamin/.cache/pre-commit/repo8_dq7otg/py_env-python3/lib/python3.12/site-packages/clang_format/__init__.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

I fixed it by manually installing `setuptools` in the environment used by `pre-commit`:

```
/home/benjamin/.cache/pre-commit/repobqdmo7_q/py_env-python3/bin/pip3 install setuptools
```

I hope the suggested fix is a general solution to this problem. But I'm unsure how `pre-commit` exactly works and I'm also not sure how I could easily test this change now.

### CODE REVIEW

**Comment by davidscn** [comment]
On 24.04, I used pipx instead of pip and it just worked for me.

**Comment by BenjaminRodenberg** [comment]
> On 24.04, I used pipx instead of pip and it just worked for me.

I also tried with `pipx` before, but this also caused some trouble (cannot recover what exactly went wrong there).

Edit: I re-installed `pre-commit` with `pipx` and I'm getting the same problem as with `apt`

**Comment by BenjaminRodenberg** [comment]
I actually think this is not an issue belonging into this repository but into https://github.com/pre-commit/mirrors-clang-format since I'm facing problems with the `clang-format` hook.

**Comment by davidscn** [comment]
Did you run pre-commit install in precice after using pipx/reinstalling pre-commit?

**Comment by fsimonis** [comment]
This is a good indicator that we should finally upgrade the clang-format version of the hook.

Newer releases don't have this issue.

**Comment by fsimonis** [comment]
Closing in favour of https://github.com/precice/precice/pull/2067

**Pull request closed without merging**
